name: Check for new commits in the upstream repo

on:
  schedule:
    - cron: "2 2 */2 * *"
  workflow_dispatch:

jobs:
  check_new_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mercuryworkshop/anuraos'
          submodules: 'recursive'
          ref: 'v2.0'
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: 'create-anura-app'
      - name: Check for new commits
        run: |
          bash
          output=$(git log --since="2 days ago")
          if [[ -n "$output" ]]; then
            ls ../
            echo "New commits! Generating new template files....."
          else
            echo "No output, exiting"
          fi
